project_id = "gsphlwjoowqkqhgthxtp"

[functions.github-oauth-callback]
verify_jwt = false

[functions.x-oauth-callback]
verify_jwt = false

[functions.delete-profile]
verify_jwt = false

[functions.analyze-github-repo]
verify_jwt = false

[functions.refresh-all-profiles]
verify_jwt = false

[functions.update-profile]
verify_jwt = false